image: ubuntu:14.04

pages:
  script:
  - apt-get install python-pip python-dev
  - pip install sphinx==1.6.7
  - pip install numpydoc
  - pip install numpy
  - pip install matplotlib
  - pip install PyQt5
  - pip install pandas
  - apt-get install make
  - cd doc
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
