image: python:3.6-stretch

pages:
  script:
  - apt-get update
  - apt-get install wine
  - pip install sphinx==1.6.7 numpydoc numpy matplotlib PyQt5 pandas
  - cd src
  - python test.py
  - cd ..
  - ls
  - cd doc
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  - ls public
  artifacts:
    paths:
    - public
  only:
  - master
